# Generated by Django 2.2.15 on 2021-02-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='Urls',
        ),
    ]
